version: "2"
services:

 postgres:
  restart: always
  image: local/postgres
  environment:
    - POSTGRES_PASSWORD='1tcadmin23'
  command: postgres

 tc_server:
  build: tc-server/build
  restart: always
  image: local/tc-server
  ports:
    - 8111:8111
  volumes_from:
    - data_teamcity
  depends_on:
    - postgres

 data_teamcity:
  image: local/data
  volumes:
    - /var/lib/teamcity_server:/var/lib/teamcity

 tc_agent:
  build: tc-agent/build
  restart: always
  image: local/tc-agent
  environment:
    - AGENT_INSTANCE_NAME=tc-agent-mmfs
    - TZ=Europe/Brussels
  expose:
    - 9090
  volumes:
    - /var/tmp/com.docker.vmnetd.socket:/var/run/docker.sock

