version: "2"
services:

 tc_server:
  restart: always
  image: local/tc-server
  ports:
    - 8111:8111
  volumes_from:
    - data_teamcity

 data_teamcity:
  image: local/data
  volumes:
    - /var/lib/teamcity_server:/var/lib/teamcity

 tc_agent:
  restart: always
  image: local/tc-agent
  environment:
    - AGENT_INSTANCE_NAME=tc-agent-mmfs
    - TZ=Europe/Brussels
  expose:
    - 9090
  volumes:
    - /var/tmp/com.docker.vmnetd.socket:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/bin/docker
